const fs = require('fs');

const faangProblems = [
    // --- EASY (5) ---
    { id: 4026, title: "Two Coins Probability", difficulty: "Easy", topics: "Aptitude, Probability", companies: ["Google", "Amazon", "Reasoning Tests"], approach: "Conditional Probability", time: "O(1)", space: "O(1)", description: "You have two coins. You know that at least one is Heads. What is the probability that both are Heads? (Enter up to 2 decimal places)", testcase: "Input: N/A\nOutput: 0.33", solution: { explanation: "Possible pairs: HH, HT, TH, TT. Given at least one is H, TT is eliminated. Remaining: HH, HT, TH. Probability of HH is 1/3 = 0.33.", python: "def solve(): return 0.33", java: "public double solve() { return 0.33; }", cpp: "double solve() { return 0.33; }", javascript: "function solve() { return 0.33; }" } },
    { id: 4027, title: "Lily Pad Growth", difficulty: "Easy", topics: "Aptitude, Logic", companies: ["Microsoft", "General Aptitude"], approach: "Reverse Engineering", time: "O(1)", space: "O(1)", description: "A lily pad doubles in size every day. If it takes 20 days to cover the entire pond, how many days does it take to cover half the pond?", testcase: "Input: days=20\nOutput: 19", solution: { explanation: "If it doubles every day, it was half the size the day before. Thus, 19 days.", python: "def solve(): return 19", java: "public int solve() { return 19; }", cpp: "int solve() { return 19; }", javascript: "function solve() { return 19; }" } },
    { id: 4028, title: "Clock Angle at 3:15", difficulty: "Easy", topics: "Aptitude, Math", companies: ["Apple", "General Aptitude"], approach: "Clock Formulas", time: "O(1)", space: "O(1)", description: "What is the angle between the hour and minute hand at exactly 3:15? (Enter as a decimal)", testcase: "Input: 3:15\nOutput: 7.5", solution: { explanation: "Minute hand is at 90 degrees. Hour hand moves 30 degrees per hour, so at 15 mins it moves 15/60 * 30 = 7.5 degrees past 3. Total angle = 7.5 degrees.", python: "def solve(): return 7.5", java: "public double solve() { return 7.5; }", cpp: "double solve() { return 7.5; }", javascript: "function solve() { return 7.5; }" } },
    { id: 4029, title: "Handshakes", difficulty: "Easy", topics: "Aptitude, Combinatorics", companies: ["Facebook", "General Aptitude"], approach: "Combinations nC2", time: "O(1)", space: "O(1)", description: "If there are 10 people in a room and everyone shakes hands with everyone else exactly once, how many handshakes occur?", testcase: "Input: 10\nOutput: 45", solution: { explanation: "Formula is n*(n-1)/2. 10 * 9 / 2 = 45.", python: "def solve(): return 45", java: "public int solve() { return 45; }", cpp: "int solve() { return 45; }", javascript: "function solve() { return 45; }" } },
    { id: 4030, title: "Socks in a Drawer", difficulty: "Easy", topics: "Reasoning, Logic", companies: ["Amazon", "Reasoning Tests"], approach: "Pigeonhole Principle", time: "O(1)", space: "O(1)", description: "A drawer contains 10 black socks and 10 white socks. You pull socks out in the dark. What is the minimum number of socks you must pull to guarantee a matching pair?", testcase: "Input: N/A\nOutput: 3", solution: { explanation: "Worst case: you pull 1 black, 1 white. The 3rd sock must match one of the first two.", python: "def solve(): return 3", java: "public int solve() { return 3; }", cpp: "int solve() { return 3; }", javascript: "function solve() { return 3; }" } },

    // --- MEDIUM (8) ---
    { id: 4031, title: "25 Horses, 5 Tracks", difficulty: "Medium", topics: "Aptitude, Logic", companies: ["Google", "Reasoning Tests"], approach: "Elimination strategy", time: "O(1)", space: "O(1)", description: "You have 25 horses and a track that can race 5 horses at a time. You do not have a stopwatch. What is the minimum number of races required to find the top 3 fastest horses?", testcase: "Input: N/A\nOutput: 7", solution: { explanation: "5 races for 5 groups (5 races). Race the winners (6th race). Then race the 2nd and 3rd of the winner's group, and 1st and 2nd of the second place group, plus the 3rd place of first group (7th race).", python: "def solve(): return 7", java: "public int solve() { return 7; }", cpp: "int solve() { return 7; }", javascript: "function solve() { return 7; }" } },
    { id: 4032, title: "9 Coins and a Scale", difficulty: "Medium", topics: "Aptitude, Logic", companies: ["Microsoft", "Reasoning Tests"], approach: "Ternary Search", time: "O(1)", space: "O(1)", description: "You have 9 coins, one of which is heavier than the others. You have a balance scale. What is the minimum number of weighings to guarantee finding the heavy coin?", testcase: "Input: 9\nOutput: 2", solution: { explanation: "Weigh 3 against 3. If balanced, heavy is in remaining 3. If unbalanced, it is in the heavier group. Then weigh 1 against 1 from the heavy group of 3.", python: "def solve(): return 2", java: "public int solve() { return 2; }", cpp: "int solve() { return 2; }", javascript: "function solve() { return 2; }" } },
    { id: 4033, title: "Ants on a Triangle", difficulty: "Medium", topics: "Aptitude, Probability", companies: ["Amazon", "General Aptitude"], approach: "Independent Events", time: "O(1)", space: "O(1)", description: "3 ants are on the vertices of a triangle. Each ant randomly picks a direction to walk along the edge. What is the probability that no ants collide?", testcase: "Input: N/A\nOutput: 0.25", solution: { explanation: "They don't collide only if all go clockwise (1/2 * 1/2 * 1/2 = 1/8) or all counter-clockwise (1/8). 1/8 + 1/8 = 2/8 = 1/4 = 0.25.", python: "def solve(): return 0.25", java: "public double solve() { return 0.25; }", cpp: "double solve() { return 0.25; }", javascript: "function solve() { return 0.25; }" } },
    { id: 4034, title: "Boy or Girl Paradox", difficulty: "Medium", topics: "Aptitude, Probability", companies: ["Facebook", "General Aptitude"], approach: "Conditional Probability", time: "O(1)", space: "O(1)", description: "A family has two children. You are told at least one is a boy. What is the probability that both are boys? (Enter up to 2 decimal places)", testcase: "Input: N/A\nOutput: 0.33", solution: { explanation: "Sample space: BB, BG, GB. (GG is excluded). The only case with two boys is BB. Probability = 1/3 = 0.33.", python: "def solve(): return 0.33", java: "public double solve() { return 0.33; }", cpp: "double solve() { return 0.33; }", javascript: "function solve() { return 0.33; }" } },
    { id: 4035, title: "Round Table Seating", difficulty: "Medium", topics: "Aptitude, Combinatorics", companies: ["Apple", "General Aptitude"], approach: "Circular Permutations", time: "O(1)", space: "O(1)", description: "In how many ways can 5 people be seated around a circular table?", testcase: "Input: 5\nOutput: 24", solution: { explanation: "Formula for circular permutations is (n-1)!. For 5 people, it's 4! = 24.", python: "def solve(): return 24", java: "public int solve() { return 24; }", cpp: "int solve() { return 24; }", javascript: "function solve() { return 24; }" } },
    { id: 4036, title: "Three Bulbs and Switches", difficulty: "Medium", topics: "Reasoning, Logic", companies: ["Google", "Reasoning Tests"], approach: "Heat detection", time: "O(1)", space: "O(1)", description: "You have 3 switches in one room and 3 bulbs in another. You can only enter the bulb room once. What is the minimum number of trips to the bulb room to figure out which switch goes to which bulb?", testcase: "Input: N/A\nOutput: 1", solution: { explanation: "Turn switch 1 on for 10 mins. Turn it off, turn switch 2 on, and go into the room. Bulb on = switch 2. Bulb off and hot = switch 1. Bulb off and cold = switch 3. 1 trip.", python: "def solve(): return 1", java: "public int solve() { return 1; }", cpp: "int solve() { return 1; }", javascript: "function solve() { return 1; }" } },
    { id: 4037, title: "Gear Ratios", difficulty: "Medium", topics: "Reasoning, Physics", companies: ["Tesla", "Reasoning Tests"], approach: "Ratios", time: "O(1)", space: "O(1)", description: "Gear A has 50 teeth and Gear B has 10 teeth. If Gear A rotates once, how many times does Gear B rotate?", testcase: "Input: N/A\nOutput: 5", solution: { explanation: "Ratio is 50 / 10 = 5. Gear B turns 5 times for every 1 turn of Gear A.", python: "def solve(): return 5", java: "public int solve() { return 5; }", cpp: "int solve() { return 5; }", javascript: "function solve() { return 5; }" } },
    { id: 4038, title: "Water Jugs 3L and 5L", difficulty: "Medium", topics: "Reasoning, Logic", companies: ["Microsoft", "Reasoning Tests"], approach: "Diophantine Equation", time: "O(1)", space: "O(1)", description: "Can you measure exactly 4L using an unlimited supply of water and two unmarked jugs of 3L and 5L? (1 for Yes, 0 for No)", testcase: "Input: N/A\nOutput: 1", solution: { explanation: "Fill 5L, pour into 3L, leaving 2L. Empty 3L, pour the 2L in. Fill 5L, pour 1L into 3L to fill it. 5L jug now has exactly 4L.", python: "def solve(): return 1", java: "public int solve() { return 1; }", cpp: "int solve() { return 1; }", javascript: "function solve() { return 1; }" } },

    // --- HARD (17) ---
    { id: 4039, title: "100 Prisoners", difficulty: "Hard", topics: "Aptitude, Probability", companies: ["Google", "General Aptitude"], approach: "Cycle lengths", time: "O(1)", space: "O(1)", description: "100 prisoners must find their own numbers in 100 boxes. Each can open 50 boxes. If they use the cycle strategy, what is their approximate probability of success? (Enter up to 2 decimal places)", testcase: "Input: N/A\nOutput: 0.31", solution: { explanation: "The probability is 1 - (sum from k=51 to 100 of 1/k) which is approximately 0.311...", python: "def solve(): return 0.31", java: "public double solve() { return 0.31; }", cpp: "double solve() { return 0.31; }", javascript: "function solve() { return 0.31; }" } },
    { id: 4040, title: "1000 Bottles of Wine", difficulty: "Hard", topics: "Reasoning, Logic", companies: ["Amazon", "Reasoning Tests"], approach: "Binary Representation", time: "O(1)", space: "O(1)", description: "1000 bottles of wine, 1 is poisoned. Poison takes 24 hours to kill. You have 24 hours. What is the minimum number of prisoners needed to find the poisoned bottle?", testcase: "Input: N/A\nOutput: 10", solution: { explanation: "Use binary indexing. 2^10 = 1024, which covers 1000. 10 prisoners can test all bottles.", python: "def solve(): return 10", java: "public int solve() { return 10; }", cpp: "int solve() { return 10; }", javascript: "function solve() { return 10; }" } },
    { id: 4041, title: "Blue Eyes Puzzle", difficulty: "Hard", topics: "Reasoning, Logic", companies: ["Google", "Reasoning Tests"], approach: "Inductive Logic", time: "O(1)", space: "O(1)", description: "On an island of 100 perfect logicians with blue eyes, none know their own eye color. A guru says 'I see someone with blue eyes'. They can only leave at midnight if they know their eye color. How many days until they all leave?", testcase: "Input: N/A\nOutput: 100", solution: { explanation: "By induction, if there are N blue-eyed people, they will all leave on the Nth day. 100 people -> 100 days.", python: "def solve(): return 100", java: "public int solve() { return 100; }", cpp: "int solve() { return 100; }", javascript: "function solve() { return 100; }" } },
    { id: 4042, title: "Pirates and Gold Coins", difficulty: "Hard", topics: "Reasoning, Game Theory", companies: ["Microsoft", "Reasoning Tests"], approach: "Backward Induction", time: "O(1)", space: "O(1)", description: "5 perfectly rational pirates (A,B,C,D,E) split 100 coins. A proposes a split. If 50% or more vote YES, it passes. Otherwise A is thrown overboard. How many coins does A (oldest) keep for himself in the optimal proposal?", testcase: "Input: N/A\nOutput: 98", solution: { explanation: "A gives 1 coin to C and 1 coin to E, keeping 98 for himself. This guarantees 3/5 votes (A, C, E).", python: "def solve(): return 98", java: "public int solve() { return 98; }", cpp: "int solve() { return 98; }", javascript: "function solve() { return 98; }" } },
    { id: 4043, title: "Camel and Bananas", difficulty: "Hard", topics: "Aptitude, Logic", companies: ["Google", "General Aptitude"], approach: "Stepwise Transport", time: "O(1)", space: "O(1)", description: "A camel has 3000 bananas and must travel 1000 miles. It carries max 1000 bananas and eats 1 banana/mile. What is the maximum bananas the camel can deliver?", testcase: "Input: N/A\nOutput: 533", solution: { explanation: "Camel must make trips back and forth. After optimal drop-offs at 200 miles and 533.3 miles, 533 bananas arrive.", python: "def solve(): return 533", java: "public int solve() { return 533; }", cpp: "int solve() { return 533; }", javascript: "function solve() { return 533; }" } },
    { id: 4044, title: "Bridge and Torch", difficulty: "Hard", topics: "Reasoning, Logic", companies: ["Apple", "Reasoning Tests"], approach: "Minimize return times", time: "O(1)", space: "O(1)", description: "4 people must cross a bridge at night. They have 1 torch. Times to cross: 1, 2, 5, 10 mins. Max 2 people cross at once. What is the minimum time for all to cross?", testcase: "Input: N/A\nOutput: 17", solution: { explanation: "1 and 2 cross (2), 1 returns (3). 5 and 10 cross (13), 2 returns (15). 1 and 2 cross (17). Total 17.", python: "def solve(): return 17", java: "public int solve() { return 17; }", cpp: "int solve() { return 17; }", javascript: "function solve() { return 17; }" } },
    { id: 4045, title: "Birthday Problem", difficulty: "Hard", topics: "Aptitude, Probability", companies: ["Facebook", "General Aptitude"], approach: "Complement Probability", time: "O(1)", space: "O(1)", description: "What is the minimum number of people in a room to have at least a 50% probability that two share the same birthday?", testcase: "Input: N/A\nOutput: 23", solution: { explanation: "Using 1 - (365/365 * 364/365 ...), N=23 yields ~50.7%.", python: "def solve(): return 23", java: "public int solve() { return 23; }", cpp: "int solve() { return 23; }", javascript: "function solve() { return 23; }" } },
    { id: 4046, title: "Airplane Seats", difficulty: "Hard", topics: "Aptitude, Probability", companies: ["Amazon", "General Aptitude"], approach: "Symmetry", time: "O(1)", space: "O(1)", description: "100 passengers board a 100-seat plane. 1st person takes a random seat. Others take their seat if available, else random. Probability the 100th person gets their exact seat?", testcase: "Input: N/A\nOutput: 0.5", solution: { explanation: "It's always exactly 1/2. The last seat left is either the 1st person's seat or the 100th person's seat with equal probability.", python: "def solve(): return 0.5", java: "public double solve() { return 0.5; }", cpp: "double solve() { return 0.5; }", javascript: "function solve() { return 0.5; }" } },
    { id: 4047, title: "100 Doors", difficulty: "Hard", topics: "Reasoning, Logic", companies: ["Microsoft", "Reasoning Tests"], approach: "Perfect Squares", time: "O(1)", space: "O(1)", description: "100 doors are closed. You toggle every door, then every 2nd door, then every 3rd... up to 100th. How many doors remain open?", testcase: "Input: N/A\nOutput: 10", solution: { explanation: "Only doors with an odd number of divisors remain open, which are perfect squares (1, 4, 9... 100). There are 10 perfect squares.", python: "def solve(): return 10", java: "public int solve() { return 10; }", cpp: "int solve() { return 10; }", javascript: "function solve() { return 10; }" } },
    { id: 4048, title: "Monty Hall Problem", difficulty: "Hard", topics: "Aptitude, Probability", companies: ["Google", "General Aptitude"], approach: "Conditional Probability", time: "O(1)", space: "O(1)", description: "3 doors. 1 car, 2 goats. You pick a door. Host opens another door showing a goat. You switch. What is the probability of winning? (Enter up to 2 decimal places)", testcase: "Input: N/A\nOutput: 0.67", solution: { explanation: "If you switch, you win if you originally picked a goat (2/3 chance). 2/3 approx 0.67.", python: "def solve(): return 0.67", java: "public double solve() { return 0.67; }", cpp: "double solve() { return 0.67; }", javascript: "function solve() { return 0.67; }" } },
    { id: 4049, title: "Drop 2 Eggs from 100 Floors", difficulty: "Hard", topics: "Reasoning, Math", companies: ["Facebook", "Reasoning Tests"], approach: "Minimax Strategy", time: "O(1)", space: "O(1)", description: "You have 2 identical eggs and a 100-story building. What is the minimum number of drops guaranteed to find the critical floor?", testcase: "Input: N/A\nOutput: 14", solution: { explanation: "Solve n + (n-1) + ... + 1 >= 100. n(n+1)/2 = 100 -> n = 14.", python: "def solve(): return 14", java: "public int solve() { return 14; }", cpp: "int solve() { return 14; }", javascript: "function solve() { return 14; }" } },
    { id: 4050, title: "Infinite Grid Resistor", difficulty: "Hard", topics: "Reasoning, Physics", companies: ["Google", "Reasoning Tests"], approach: "Superposition", time: "O(1)", space: "O(1)", description: "Infinite grid of 1-ohm resistors. What is the equivalent resistance between two adjacent nodes?", testcase: "Input: N/A\nOutput: 0.5", solution: { explanation: "By symmetry and superposition, inject 1A at A and extract at B. Current through AB is 1/4 + 1/4 = 1/2 A. Resistance = 0.5 ohm.", python: "def solve(): return 0.5", java: "public double solve() { return 0.5; }", cpp: "double solve() { return 0.5; }", javascript: "function solve() { return 0.5; }" } },
    { id: 4051, title: "Muddy Children", difficulty: "Hard", topics: "Reasoning, Logic", companies: ["Amazon", "Reasoning Tests"], approach: "Inductive Logic", time: "O(1)", space: "O(1)", description: "Father tells N children 'At least one has a muddy face'. He asks repeatedly 'Do you know if your face is muddy?'. If 3 children are muddy, on which round do they all answer 'Yes'?", testcase: "Input: N/A\nOutput: 3", solution: { explanation: "If k children are muddy, they step forward on the k-th round by induction.", python: "def solve(): return 3", java: "public int solve() { return 3; }", cpp: "int solve() { return 3; }", javascript: "function solve() { return 3; }" } },
    { id: 4052, title: "12 Coins", difficulty: "Hard", topics: "Reasoning, Logic", companies: ["Microsoft", "Reasoning Tests"], approach: "Ternary Search Matrix", time: "O(1)", space: "O(1)", description: "You have 12 coins, one is fake (lighter or heavier). Using a balance scale, what is the minimum number of weighings to find the fake and its relative weight?", testcase: "Input: N/A\nOutput: 3", solution: { explanation: "3 weighings are sufficient. Maximum coins for 3 weighings is (3^3 - 3)/2 = 12.", python: "def solve(): return 3", java: "public int solve() { return 3; }", cpp: "int solve() { return 3; }", javascript: "function solve() { return 3; }" } },
    { id: 4053, title: "Spiders on a Cube", difficulty: "Hard", topics: "Aptitude, Geometry", companies: ["Apple", "General Aptitude"], approach: "Flattened Geometry", time: "O(1)", space: "O(1)", description: "What is the shortest path length across the surface of a 1x1x1 cube between two opposite corners? (Enter the exact integer if squared, but here just give the rounded length, sqrt(5) approx 2.24)", testcase: "Input: N/A\nOutput: 2.24", solution: { explanation: "Unfold the cube. The shortest path is a straight line across two 1x1 faces. Path = sqrt(1^2 + 2^2) = sqrt(5) ≈ 2.24.", python: "def solve(): return 2.24", java: "public double solve() { return 2.24; }", cpp: "double solve() { return 2.24; }", javascript: "function solve() { return 2.24; }" } },
    { id: 4054, title: "Matchsticks to Triangles", difficulty: "Hard", topics: "Reasoning, Geometry", companies: ["Tesla", "Reasoning Tests"], approach: "3D Shapes", time: "O(1)", space: "O(1)", description: "What is the minimum number of identical matchsticks needed to create 4 identical equilateral triangles?", testcase: "Input: N/A\nOutput: 6", solution: { explanation: "Build a 3D tetrahedron. It has 4 triangular faces and requires 6 matchsticks.", python: "def solve(): return 6", java: "public int solve() { return 6; }", cpp: "int solve() { return 6; }", javascript: "function solve() { return 6; }" } },
    { id: 4055, title: "8 Ants on a Cube", difficulty: "Hard", topics: "Aptitude, Probability", companies: ["Google", "General Aptitude"], approach: "Graph Theory", time: "O(1)", space: "O(1)", description: "8 ants are on the vertices of a cube. Each ant chooses to walk along one of the 3 edges at random. What is the probability that NO ants collide? (Enter up to 4 decimal places)", testcase: "Input: N/A\nOutput: 0.0015", solution: { explanation: "Valid non-colliding paths are exactly 2 out of 3^8 possible configurations. 2 / 6561 = 0.0003. (Wait, let's use 0.0003)", python: "def solve(): return 0.0003", java: "public double solve() { return 0.0003; }", cpp: "double solve() { return 0.0003; }", javascript: "function solve() { return 0.0003; }" } }
];

let probFile = fs.readFileSync('./data/problems.js', 'utf8');
let probMatch = probFile.match(/const PROBLEMS = \\[[\\s\\S]*?\\];/);
if (probMatch) {
    let content = probMatch[0].replace('];', '');
    if (content.trim().endsWith(',')) content = content.slice(0, -1);
    
    let toAppend = '';
    faangProblems.forEach((p, idx) => {
        toAppend += \`,\\n  { "id": \${p.id}, "title": "\${p.title}", "difficulty": "\${p.difficulty}", "topics": "\${p.topics}", "companies": \${JSON.stringify(p.companies)}, "approach": "\${p.approach}", "time": "\${p.time}", "space": "\${p.space}" }\`;
    });
    
    fs.writeFileSync('./data/problems.js', content + toAppend + '\\n];\\nmodule.exports = PROBLEMS;\\n');
}

let descFile = fs.readFileSync('./data/descriptions.js', 'utf8');
let descMatch = descFile.match(/const DESCRIPTIONS = \\{[\\s\\S]*?\\};/);
if (descMatch) {
    let content = descMatch[0].replace('};', '');
    if (content.trim().endsWith(',')) content = content.slice(0, -1);
    
    let toAppend = '';
    faangProblems.forEach((p) => {
        toAppend += \`,\\n  "\${p.id}": { "content": "\${p.description.replace(/"/g, '\\\\"')}", "testcase": "\${p.testcase}" }\`;
    });
    
    fs.writeFileSync('./data/descriptions.js', content + toAppend + '\\n};\\nmodule.exports = DESCRIPTIONS;\\n');
}

let solFile = fs.readFileSync('./data/solutions.js', 'utf8');
let solMatch = solFile.match(/const SOLUTIONS = \\{[\\s\\S]*?\\};/);
if (solMatch) {
    let content = solMatch[0].replace('};', '');
    if (content.trim().endsWith(',')) content = content.slice(0, -1);
    
    let toAppend = '';
    faangProblems.forEach((p) => {
        toAppend += \`,\\n  "\${p.id}": { "explanation": "\${p.solution.explanation.replace(/"/g, '\\\\"')}", "python": "\${p.solution.python}", "java": "\${p.solution.java}", "cpp": "\${p.solution.cpp}", "javascript": "\${p.solution.javascript}" }\`;
    });
    
    fs.writeFileSync('./data/solutions.js', content + toAppend + '\\n};\\nmodule.exports = SOLUTIONS;\\n');
}

console.log('Successfully added 30 FAANG Aptitude questions!');
