const fs = require('fs');
const path = require('path');

// To run this, you will need to install the anthropic SDK:
// npm install @anthropic-ai/sdk dotenv
// And create a .env file with ANTHROPIC_API_KEY=your_key

const { Anthropic } = require('@anthropic-ai/sdk');
const PROBLEMS = require('./data/problems');

const anthropic = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY || 'YOUR_API_KEY_HERE'
});

const SOLUTIONS_FILE = path.join(__dirname, 'data', 'solutions.js');

async function loadExistingSolutions() {
    try {
        if (fs.existsSync(SOLUTIONS_FILE)) {
            const content = fs.readFileSync(SOLUTIONS_FILE, 'utf8');
            // Basic extraction if it exports an object. 
            // For safety, we will just parse it dynamically or start fresh.
            // In a real run, we'd only fetch missing ones.
            const match = content.match(/const SOLUTIONS = ({[\s\S]*});?\s*module\.exports/);
            if (match) {
                // Using eval to parse the JS object into memory
                return eval(`(${match[1]})`);
            }
        }
    } catch (e) {
        console.error("Could not parse existing solutions:", e.message);
    }
    return {};
}

async function fetchSolution(problem) {
    console.log(`Generating solution for #${problem.id}: ${problem.title}...`);
    try {
        const msg = await anthropic.messages.create({
            model: "claude-3-5-sonnet-20241022",
            max_tokens: 1500,
            system: "You are an expert algorithms instructor. Generate solutions in Python, Java, and C++.",
            messages: [{
                role: "user",
                content: `Solve LeetCode #${problem.id}: "${problem.title}" (${problem.difficulty}).
Topic: ${problem.topics}
Optimal approach: ${problem.approach}
Time: ${problem.time} | Space: ${problem.space}

Return ONLY valid JSON in this exact format, with no other text, markdown blocks, or explanation outside the JSON:
{
  "explanation": "A concise 2-3 sentence explanation of the approach.",
  "python": "def python_solution(): ...",
  "java": "public java_solution() { ... }",
  "cpp": "cpp_solution() { ... }"
}`
            }]
        });

        let text = msg.content[0].text;
        text = text.replace(/\`\`\`json/g, '').replace(/\`\`\`/g, '').trim();
        return JSON.parse(text);
    } catch (e) {
        console.error(`Error generating for #${problem.id}:`, e.message);
        return null;
    }
}

async function generateAll() {
    if (!process.env.ANTHROPIC_API_KEY && !anthropic.apiKey) {
        console.error("Please set ANTHROPIC_API_KEY environment variable.");
        return;
    }

    const solutions = await loadExistingSolutions();
    let generatedCount = 0;

    for (const problem of PROBLEMS) {
        if (solutions[problem.id] && solutions[problem.id].python && !solutions[problem.id].python.includes('pending')) {
            console.log(`Skipping #${problem.id} (already exists)`);
            continue;
        }

        const newSolution = await fetchSolution(problem);
        if (newSolution) {
            solutions[problem.id] = newSolution;
            generatedCount++;
            
            // Save after every successful generation to prevent data loss
            saveSolutions(solutions);
        }
        
        // Rate limiting pause
        await new Promise(r => setTimeout(r, 2000));
    }
    
    console.log(`\\n✅ Finished generating ${generatedCount} new solutions!`);
}

function saveSolutions(solutionsObj) {
    let jsContent = `// Pre-written detailed solutions for each LeetCode problem\\n`;
    jsContent += `// Auto-generated by AI script\\n\\n`;
    jsContent += `const SOLUTIONS = {\\n\\n`;

    for (const [id, sol] of Object.entries(solutionsObj)) {
        jsContent += `    ${id}: {\\n`;
        jsContent += `        explanation: \`${(sol.explanation || '').replace(/\`/g, '\\\\`')}\`,\\n`;
        jsContent += `        python: \`${(sol.python || '').replace(/\`/g, '\\\\`')}\`,\\n`;
        jsContent += `        java: \`${(sol.java || '').replace(/\`/g, '\\\\`')}\`,\\n`;
        jsContent += `        cpp: \`${(sol.cpp || '').replace(/\`/g, '\\\\`')}\`\\n`;
        jsContent += `    },\\n\\n`;
    }

    jsContent += `};\\n\\nmodule.exports = SOLUTIONS;\\n`;
    fs.writeFileSync(SOLUTIONS_FILE, jsContent, 'utf8');
}

// generateAll();
